version: '3.9'

services:
  app:
    build:
      context: '.'
      dockerfile: dockerfile
    container_name: listmachine_app
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './:/var/www
      - './public:/var/www/html/public'
    depends_on:
      - pgsql
    networks:
      - listmachine
      - web 

  pgsql:
    image: 'postgres:18-alpine'
    container_name: listmachine_pgsql
    restart: always
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
    networks:
      - listmachine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  listmachine:
    external: true
  web:
    external: true

volumes:
  pgsql_data:
    driver: local
